CREATE TABLE "SSOLOG"
  (
    "UUID"       VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "GUUKEY"     VARCHAR2(50 BYTE),
    "USERID"     VARCHAR2(100 BYTE),
    "USERIP"     VARCHAR2(100 BYTE),
    "USERACTIVE" VARCHAR2(20 BYTE),
    "ACTIVETIME" DATE,
    CONSTRAINT "SSOLOG_PK" PRIMARY KEY ("UUID")
 );
 
 CREATE TABLE "SSORECORD"
  (
    "GUUKEY"   VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "TIMEKEY"  VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "USERID"   VARCHAR2(20 BYTE) NOT NULL ENABLE,
    "USERNAME" VARCHAR2(20 BYTE),
    "USERPWD" VARCHAR2(200 BYTE),
    "LOGINTIME" DATE,
    "TIMEOUTTIME" DATE,
    CONSTRAINT "SSORECORD_PK" PRIMARY KEY ("GUUKEY") 
 );

CREATE TABLE "SSOUSER"
  (
    "USERID"   VARCHAR2(100 BYTE) NOT NULL ENABLE,
    "USERSEX"  NUMBER,
    "USERNAME" VARCHAR2(100 BYTE),
    "USERPWD" VARCHAR2(200 BYTE),
    "LIBCODE"  VARCHAR2(100 BYTE),
    "LIBNAME"  VARCHAR2(100 BYTE),
    CONSTRAINT "SSOUSER_PK" PRIMARY KEY ("USERID")
);